name: CI / CD for .Net Core Project

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出程式碼
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: 設定 .NET 環境
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: 恢復 NuGet 套件
      - name: Restore dependencies
        run: dotnet restore

      # Step 4: 執行 NUnit 測試
      - name: Run tests
        run: dotnet test --no-build --verbosity normal