name: CI / CD for .Net Core Project

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 檢出程式碼
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: 設定 .NET 環境
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: 恢復 NuGet 套件
      - name: Restore dependencies
        run: dotnet restore

      # 執行 App.Tests 測試
      - name: Run Application.Tests
        run: dotnet test ./Application.Tests/Application.Tests.csproj --verbosity normal

      # 執行 Domain.Tests 測試
      - name: Run Domain.Tests
        run: dotnet test ./Domain.Tests/Domain.Tests.csproj --verbosity normal

      # 執行 EcommerceBackend.Tests 測試
      - name: Run EcommerceBackend.Tests
        run: dotnet test ./EcommerceBackend.Tests/EcommerceBackend.Tests.csproj --verbosity normal
      
      # 登入 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 建立 & 推送 Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce-backend:latest