// <auto-generated />
using System;
using DataSource.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataSource.Migrations
{
    [DbContext(typeof(EcommerceDBContext))]
    [Migration("20251205094701_Add_Payment_Performance_Index")]
    partial class Add_Payment_Performance_Index
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Domain.Entities.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Discounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4487),
                            DiscountAmount = 100,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4487)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4489),
                            DiscountAmount = 199,
                            EndDate = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            StartDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4490)
                        });
                });

            modelBuilder.Entity("Domain.Entities.FavoriteProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId")
                        .IsUnique();

                    b.ToTable("FavoriteProducts");
                });

            modelBuilder.Entity("Domain.Entities.Kind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Kinds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "clothes"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PayWay")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PickedUpAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Receiver")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecieveStore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecieveWay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecordCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ShippingPrice")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("RecordCode")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Domain.Entities.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductPrice")
                        .HasColumnType("integer");

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Domain.Entities.OrderStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("StepStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderSteps");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<byte>("PaymentStatus")
                        .HasColumnType("smallint");

                    b.Property<int>("TenantConfigId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("TenantConfigId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HowToWash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImg = "https://ponggoodbf.com/img/coat1.jpg",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4250),
                            Features = "其實我也不知道要說什麼...a",
                            HowToWash = "洗衣機（水溫40度）, 不可乾洗, 不可烘乾。本商品會在流汗或淋雨弄濕時，或因摩擦而染色到其他衣物上，敬請注意。",
                            Material = "聚酯纖維, 聚氨酯纖維",
                            Title = "超時尚流蘇几皮外套",
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4252)
                        },
                        new
                        {
                            Id = 2,
                            CoverImg = "https://ponggoodbf.com/img/coat4.jpg",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4254),
                            Features = "其實我也不知道要說什麼...a",
                            HowToWash = "洗衣機（水溫40度）, 不可乾洗, 不可烘乾。本商品會在流汗或淋雨弄濕時，或因摩擦而染色到其他衣物上，敬請注意。",
                            Material = "聚酯纖維, 聚氨酯纖維",
                            Title = "紫色格紋大衣",
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4254)
                        },
                        new
                        {
                            Id = 3,
                            CoverImg = "https://ponggoodbf.com/img/coat3.jpg",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4255),
                            Features = "其實我也不知道要說什麼...a",
                            HowToWash = "洗衣機（水溫40度）, 不可乾洗, 不可烘乾。本商品會在流汗或淋雨弄濕時，或因摩擦而染色到其他衣物上，敬請注意。",
                            Material = "聚酯纖維, 聚氨酯纖維",
                            Title = "超質感綠色皮衣",
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4256)
                        },
                        new
                        {
                            Id = 4,
                            CoverImg = "https://ponggoodbf.com/img/coat2.jpg",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4257),
                            Features = "其實我也不知道要說什麼...a",
                            HowToWash = "洗衣機（水溫40度）, 不可乾洗, 不可烘乾。本商品會在流汗或淋雨弄濕時，或因摩擦而染色到其他衣物上，敬請注意。",
                            Material = "聚酯纖維, 聚氨酯纖維",
                            Title = "海島風情黑色短袖襯衫",
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4257)
                        },
                        new
                        {
                            Id = 5,
                            CoverImg = "https://ponggoodbf.com/img/coat5.jpg",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4258),
                            Features = "其實我也不知道要說什麼...a",
                            HowToWash = "洗衣機（水溫40度）, 不可乾洗, 不可烘乾。本商品會在流汗或淋雨弄濕時，或因摩擦而染色到其他衣物上，敬請注意。",
                            Material = "聚酯纖維, 聚氨酯纖維",
                            Title = "帥氣單寧",
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4259)
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDiscounts");
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://ponggoodbf.com/img/coat1.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://ponggoodbf.com/img/coat2.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "https://ponggoodbf.com/img/coat3.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "https://ponggoodbf.com/img/coat4.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "https://ponggoodbf.com/img/coat5.jpg",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "https://ponggoodbf.com/img/coat2.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "https://ponggoodbf.com/img/coat3.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "https://ponggoodbf.com/img/coat4.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "https://ponggoodbf.com/img/coat5.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "https://ponggoodbf.com/img/coat1.jpg",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "https://ponggoodbf.com/img/coat3.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "https://ponggoodbf.com/img/coat5.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "https://ponggoodbf.com/img/coat4.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "https://ponggoodbf.com/img/coat2.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "https://ponggoodbf.com/img/coat1.jpg",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "https://ponggoodbf.com/img/coat3.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "https://ponggoodbf.com/img/coat5.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "https://ponggoodbf.com/img/coat4.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "https://ponggoodbf.com/img/coat2.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "https://ponggoodbf.com/img/coat1.jpg",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "https://ponggoodbf.com/img/coat3.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "https://ponggoodbf.com/img/coat5.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "https://ponggoodbf.com/img/coat4.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "https://ponggoodbf.com/img/coat2.jpg",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "https://ponggoodbf.com/img/coat1.jpg",
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KindId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KindId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductKinds");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMaterials");
                });

            modelBuilder.Entity("Domain.Entities.ProductTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TagId");

                    b.ToTable("ProductTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            TagId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            TagId = 4
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            TagId = 2
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 3,
                            TagId = 3
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 3,
                            TagId = 5
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 3,
                            TagId = 5
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 4,
                            TagId = 6
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 5,
                            TagId = 8
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 5,
                            TagId = 8
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 5,
                            TagId = 9
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VariantPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4398),
                            ProductId = 1,
                            SKU = "BLACK-S",
                            SizeId = 1,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4398),
                            VariantPrice = 99
                        },
                        new
                        {
                            Id = 2,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4401),
                            ProductId = 1,
                            SKU = "BLACK-L",
                            SizeId = 3,
                            Stock = 16,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4402),
                            VariantPrice = 283
                        },
                        new
                        {
                            Id = 3,
                            Color = "米",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4403),
                            ProductId = 1,
                            SKU = "WHEAT-L",
                            SizeId = 3,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4403),
                            VariantPrice = 150
                        },
                        new
                        {
                            Id = 4,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4405),
                            ProductId = 1,
                            SKU = "BROWN-M",
                            SizeId = 2,
                            Stock = 17,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4405),
                            VariantPrice = 199
                        },
                        new
                        {
                            Id = 5,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4407),
                            ProductId = 1,
                            SKU = "BROWN-L",
                            SizeId = 3,
                            Stock = 20,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4407),
                            VariantPrice = 211
                        },
                        new
                        {
                            Id = 6,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4408),
                            ProductId = 2,
                            SKU = "BLACK-S",
                            SizeId = 1,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4409),
                            VariantPrice = 99
                        },
                        new
                        {
                            Id = 7,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4410),
                            ProductId = 2,
                            SKU = "BLACK-L",
                            SizeId = 3,
                            Stock = 16,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4410),
                            VariantPrice = 283
                        },
                        new
                        {
                            Id = 8,
                            Color = "米",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4411),
                            ProductId = 2,
                            SKU = "WHEAT-L",
                            SizeId = 3,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4411),
                            VariantPrice = 150
                        },
                        new
                        {
                            Id = 9,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4412),
                            ProductId = 2,
                            SKU = "BROWN-M",
                            SizeId = 2,
                            Stock = 17,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4413),
                            VariantPrice = 199
                        },
                        new
                        {
                            Id = 10,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4414),
                            ProductId = 3,
                            SKU = "BLACK-S",
                            SizeId = 1,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4414),
                            VariantPrice = 99
                        },
                        new
                        {
                            Id = 11,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4415),
                            ProductId = 3,
                            SKU = "BLACK-L",
                            SizeId = 3,
                            Stock = 16,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4416),
                            VariantPrice = 283
                        },
                        new
                        {
                            Id = 12,
                            Color = "米",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4417),
                            ProductId = 3,
                            SKU = "WHEAT-L",
                            SizeId = 3,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4417),
                            VariantPrice = 150
                        },
                        new
                        {
                            Id = 13,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4418),
                            ProductId = 3,
                            SKU = "BROWN-M",
                            SizeId = 2,
                            Stock = 17,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4418),
                            VariantPrice = 199
                        },
                        new
                        {
                            Id = 14,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4442),
                            ProductId = 3,
                            SKU = "BROWN-L",
                            SizeId = 3,
                            Stock = 20,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4442),
                            VariantPrice = 211
                        },
                        new
                        {
                            Id = 15,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4443),
                            ProductId = 4,
                            SKU = "BLACK-S",
                            SizeId = 1,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4444),
                            VariantPrice = 99
                        },
                        new
                        {
                            Id = 16,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4445),
                            ProductId = 4,
                            SKU = "BLACK-L",
                            SizeId = 3,
                            Stock = 16,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4445),
                            VariantPrice = 283
                        },
                        new
                        {
                            Id = 17,
                            Color = "米",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4446),
                            ProductId = 4,
                            SKU = "WHEAT-L",
                            SizeId = 3,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4446),
                            VariantPrice = 150
                        },
                        new
                        {
                            Id = 18,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4447),
                            ProductId = 4,
                            SKU = "BROWN-M",
                            SizeId = 2,
                            Stock = 17,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4448),
                            VariantPrice = 199
                        },
                        new
                        {
                            Id = 19,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4449),
                            ProductId = 4,
                            SKU = "BROWN-L",
                            SizeId = 3,
                            Stock = 20,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4449),
                            VariantPrice = 211
                        },
                        new
                        {
                            Id = 20,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4450),
                            ProductId = 5,
                            SKU = "BLACK-S",
                            SizeId = 1,
                            Stock = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4450),
                            VariantPrice = 99
                        },
                        new
                        {
                            Id = 21,
                            Color = "黑",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4451),
                            ProductId = 5,
                            SKU = "BLACK-L",
                            SizeId = 3,
                            Stock = 16,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4452),
                            VariantPrice = 283
                        },
                        new
                        {
                            Id = 22,
                            Color = "米",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4453),
                            ProductId = 5,
                            SKU = "WHEAT-L",
                            SizeId = 3,
                            Stock = 3,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4453),
                            VariantPrice = 150
                        },
                        new
                        {
                            Id = 23,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4454),
                            ProductId = 5,
                            SKU = "BROWN-M",
                            SizeId = 2,
                            Stock = 17,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4455),
                            VariantPrice = 199
                        },
                        new
                        {
                            Id = 24,
                            Color = "咖啡",
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4456),
                            ProductId = 5,
                            SKU = "BROWN-L",
                            SizeId = 3,
                            Stock = 20,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4456),
                            VariantPrice = 211
                        });
                });

            modelBuilder.Entity("Domain.Entities.ProductVariantDiscount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VariantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.HasIndex("VariantId");

                    b.HasIndex("VariantId", "DiscountId");

                    b.ToTable("ProductVariantDiscounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4501),
                            DiscountId = 1,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4502),
                            VariantId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4504),
                            DiscountId = 1,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4505),
                            VariantId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4505),
                            DiscountId = 1,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4506),
                            VariantId = 8
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4507),
                            DiscountId = 1,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4507),
                            VariantId = 11
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4508),
                            DiscountId = 1,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4508),
                            VariantId = 12
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4509),
                            DiscountId = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4509),
                            VariantId = 19
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4510),
                            DiscountId = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4510),
                            VariantId = 22
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4511),
                            DiscountId = 2,
                            UpdatedAt = new DateTime(2025, 12, 5, 9, 47, 1, 421, DateTimeKind.Utc).AddTicks(4511),
                            VariantId = 24
                        });
                });

            modelBuilder.Entity("Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ShipmentStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Domain.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SizeValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SizeValue = "S"
                        },
                        new
                        {
                            Id = 2,
                            SizeValue = "M"
                        },
                        new
                        {
                            Id = 3,
                            SizeValue = "L"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "t-shirt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "shirt"
                        },
                        new
                        {
                            Id = 3,
                            Name = "jeans"
                        },
                        new
                        {
                            Id = 4,
                            Name = "shorts"
                        },
                        new
                        {
                            Id = 5,
                            Name = "windcoat"
                        },
                        new
                        {
                            Id = 6,
                            Name = "knitting"
                        },
                        new
                        {
                            Id = 7,
                            Name = "accessories"
                        },
                        new
                        {
                            Id = 8,
                            Name = "new-arrival"
                        },
                        new
                        {
                            Id = 9,
                            Name = "limit-time-offer"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TenantConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HashIV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MerchantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TenantConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HashIV = "EkRm7iFT261dpevs",
                            MerchantId = "3002607",
                            SecretKey = "pwFHCqoQZGmho4w6"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("GoogleId")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NickName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserShipAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecieveStore")
                        .HasColumnType("text");

                    b.Property<string>("RecieveWay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserShipAddresses");
                });

            modelBuilder.Entity("Domain.Interfaces.Repositories.PaymentUpdateResult", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PayWay")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.Property<bool>("Updated")
                        .HasColumnType("boolean");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CartItem", b =>
                {
                    b.HasOne("Domain.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.Entities.FavoriteProduct", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("FavoriteProducts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.HasOne("Domain.Entities.UserShipAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.OrderProduct", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("OrderProducts")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.Entities.OrderStep", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("OrderSteps")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("Domain.Entities.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TenantConfig", "TenantConfig")
                        .WithMany("Payments")
                        .HasForeignKey("TenantConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("TenantConfig");
                });

            modelBuilder.Entity("Domain.Entities.ProductDiscount", b =>
                {
                    b.HasOne("Domain.Entities.Discount", "Discount")
                        .WithMany()
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductImage", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductKind", b =>
                {
                    b.HasOne("Domain.Entities.Kind", "Kind")
                        .WithMany("ProductKinds")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductKinds")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kind");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductMaterial", b =>
                {
                    b.HasOne("Domain.Entities.Material", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Entities.ProductTag", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductTags")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tag", "Tag")
                        .WithMany("ProductTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Entities.ProductVariant", b =>
                {
                    b.HasOne("Domain.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Size", "Size")
                        .WithMany("ProductVariants")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Domain.Entities.ProductVariantDiscount", b =>
                {
                    b.HasOne("Domain.Entities.Discount", "Discount")
                        .WithMany("ProductVariantDiscounts")
                        .HasForeignKey("DiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ProductVariant", "ProductVariant")
                        .WithMany("ProductVariantDiscounts")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Domain.Entities.Shipment", b =>
                {
                    b.HasOne("Domain.Entities.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Domain.Entities.UserShipAddress", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserShipAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("Domain.Entities.Discount", b =>
                {
                    b.Navigation("ProductVariantDiscounts");
                });

            modelBuilder.Entity("Domain.Entities.Kind", b =>
                {
                    b.Navigation("ProductKinds");
                });

            modelBuilder.Entity("Domain.Entities.Material", b =>
                {
                    b.Navigation("ProductMaterials");
                });

            modelBuilder.Entity("Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("OrderSteps");

                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Navigation("FavoriteProducts");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductKinds");

                    b.Navigation("ProductMaterials");

                    b.Navigation("ProductTags");

                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Domain.Entities.ProductVariant", b =>
                {
                    b.Navigation("OrderProducts");

                    b.Navigation("ProductVariantDiscounts");
                });

            modelBuilder.Entity("Domain.Entities.Size", b =>
                {
                    b.Navigation("ProductVariants");
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Navigation("ProductTags");
                });

            modelBuilder.Entity("Domain.Entities.TenantConfig", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("FavoriteProducts");

                    b.Navigation("UserShipAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
